name: CI Memory

on: 
 push:
  branches:
   - develop

jobs:
 test-memory:
  runs-on: self-hosted
  steps:
   - name: Check repo
     uses: actions/checkout@v2

   - name: Execution sur les fichiers JPG
     run: find . -iname "*.jpg" -exec file {} \;

 build-memory:
  needs: test-memory
  runs-on: self-hosted
  steps:
   - name: Check repo
     uses: actions/checkout@v2

   - name: Build Docker image
     run: docker build -t maena/memory .

 push-memory:
  needs: build-memory
  runs-on: self-hosted
  steps: 
   - name: auth DockerHub
     run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

   - name: Push Docker image
     run: docker push maena/memory

 deploy-memory:
  needs: push-memory
  runs-on: self-hosted
  steps:
   - name: Connexion ssh
     run: ssh root@7a35929293af 'docker pull maena/memory && docker run -d -p 80:8080 maena/memory'
